/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as PostCallRouteImport } from './routes/post-call'
import { Route as ClientRouteImport } from './routes/client'
import { Route as CallsTodayRouteImport } from './routes/calls-today'
import { Route as ActionItemsRouteImport } from './routes/action-items'
import { Route as IndexRouteImport } from './routes/index'

const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const PostCallRoute = PostCallRouteImport.update({
  id: '/post-call',
  path: '/post-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsTodayRoute = CallsTodayRouteImport.update({
  id: '/calls-today',
  path: '/calls-today',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionItemsRoute = ActionItemsRouteImport.update({
  id: '/action-items',
  path: '/action-items',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/calls-today': typeof CallsTodayRoute
  '/client': typeof ClientRoute
  '/post-call': typeof PostCallRoute
  '/proposals': typeof ProposalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/calls-today': typeof CallsTodayRoute
  '/client': typeof ClientRoute
  '/post-call': typeof PostCallRoute
  '/proposals': typeof ProposalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/calls-today': typeof CallsTodayRoute
  '/client': typeof ClientRoute
  '/post-call': typeof PostCallRoute
  '/proposals': typeof ProposalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-items'
    | '/calls-today'
    | '/client'
    | '/post-call'
    | '/proposals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-items'
    | '/calls-today'
    | '/client'
    | '/post-call'
    | '/proposals'
  id:
    | '__root__'
    | '/'
    | '/action-items'
    | '/calls-today'
    | '/client'
    | '/post-call'
    | '/proposals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionItemsRoute: typeof ActionItemsRoute
  CallsTodayRoute: typeof CallsTodayRoute
  ClientRoute: typeof ClientRoute
  PostCallRoute: typeof PostCallRoute
  ProposalsRoute: typeof ProposalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-call': {
      id: '/post-call'
      path: '/post-call'
      fullPath: '/post-call'
      preLoaderRoute: typeof PostCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls-today': {
      id: '/calls-today'
      path: '/calls-today'
      fullPath: '/calls-today'
      preLoaderRoute: typeof CallsTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-items': {
      id: '/action-items'
      path: '/action-items'
      fullPath: '/action-items'
      preLoaderRoute: typeof ActionItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionItemsRoute: ActionItemsRoute,
  CallsTodayRoute: CallsTodayRoute,
  ClientRoute: ClientRoute,
  PostCallRoute: PostCallRoute,
  ProposalsRoute: ProposalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
